apiVersion: v2
name: pagopa-print-payment-notice-functions
description: Microservice that handles services for notice print generation
type: application
version: 0.39.0
appVersion: 1.0.0-1-hotfix-zip-function
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
